services:
  mcp-gateway:
    build:
      context: ../
      dockerfile: gateway/Dockerfile
      target: builder
    container_name: omni-mcp-gateway
    env_file:
      - ../.env
      - ../gateway/.env
      - ../secrets/.env.development.local
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - GATEWAY_PORT=37373
    volumes:
      - ../gateway/src:/app/gateway/src:ro
      - ../gateway/package.json:/app/gateway/package.json:ro
      - ../shared:/app/shared:ro
    command:
      - sh
      - "-c"
      - cd gateway && pnpm dev
    ports:
      - "37373:37373"
      - "9229:9229"
    networks:
      - mcp-network
    depends_on:
      - linear-mcp-server
  linear-mcp-server:
    build:
      context: ../
      dockerfile: servers/linear-mcp-server/Dockerfile
      target: builder
    container_name: omni-linear-mcp-server
    env_file:
      - ../.env
      - ../servers/.env
      - ../servers/linear-mcp-server/.env
      - ../secrets/.env.development.local
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3001
    volumes:
      - ../servers/linear-mcp-server/src:/app/servers/linear-mcp-server/src:ro
      - ../servers/linear-mcp-server/package.json:/app/servers/linear-mcp-server/package.json:ro
      - ../shared:/app/shared:ro
    command:
      - sh
      - "-c"
      - cd servers/linear-mcp-server && pnpm dev
    ports:
      - "3001:3001"
      - "9230:9229"
    networks:
      - mcp-network
    healthcheck:
      test:
        - CMD
        - curl
        - "-f"
        - http://localhost:3001/health
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
  # ==========================================================================
  # PostgreSQL 17 Database with Pagila Sample Data
  # ==========================================================================
  postgres-pagila:
    image: postgres:17
    container_name: omni-postgres-pagila
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pagila
    ports:
      - "5432:5432"
    volumes:
      - postgres_pagila_data:/var/lib/postgresql/data
      - ../data/pagila:/docker-entrypoint-initdb.d:ro
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pagila"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
networks:
  mcp-network:
    driver: bridge

volumes:
  postgres_pagila_data:
