# =============================================================================
# Omni MCP - Development Configuration
# =============================================================================
# Complete service definitions for development environment

services:
  # ==========================================================================
  # MCP Gateway Service
  # ==========================================================================
  mcp-gateway:
    build:
      context: ../
      dockerfile: gateway/Dockerfile
      target: builder
    container_name: omni-mcp-gateway
    env_file:
      - ../.env
      - ../gateway/.env
      - ../secrets/.env.development.local
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - GATEWAY_PORT=37373
    volumes:
      # Hot reload for development
      - ../gateway/src:/app/gateway/src:ro
      - ../gateway/package.json:/app/gateway/package.json:ro
      - ../shared:/app/shared:ro
    command: ["sh", "-c", "cd gateway && pnpm dev"]
    ports:
      - "37373:37373"
      - "9229:9229" # Node.js debug port
    networks:
      - mcp-network
    depends_on:
      - linear-mcp-server

  # ==========================================================================
  # Linear MCP Server Service
  # ==========================================================================
  linear-mcp-server:
    build:
      context: ../
      dockerfile: servers/linear-mcp-server/Dockerfile
      target: builder
    container_name: omni-linear-mcp-server
    env_file:
      - ../.env
      - ../servers/.env
      - ../servers/linear-mcp-server/.env
      - ../secrets/.env.development.local
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3001
    volumes:
      # Hot reload for development
      - ../servers/linear-mcp-server/src:/app/servers/linear-mcp-server/src:ro
      - ../servers/linear-mcp-server/package.json:/app/servers/linear-mcp-server/package.json:ro
      - ../shared:/app/shared:ro
    # Run the HTTP server instead of stdio server
    command: ["sh", "-c", "cd servers/linear-mcp-server && pnpm dev"]
    ports:
      - "3001:3001" # Expose for direct access and health checks
      - "9230:9229" # Node.js debug port (different from gateway)
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

# =============================================================================
# Networks
# =============================================================================
networks:
  mcp-network:
    driver: bridge
