services:
  gateway:
    image: mcp/gateway:latest
    build:
      context: ..
      dockerfile: ./gateway/Dockerfile
    container_name: mcp-gateway-dev
    ports:
      - "37373:37373" # Expose the gateway port
    networks:
      - mcp-net
    depends_on:
      - filesystem
      - linear

  filesystem:
    image: mcp/filesystem:latest
    container_name: mcp-filesystem-dev
    command: ["/data", "/uploads"]
    networks:
      - mcp-net
    volumes:
      - ../data/files:/data:rw
      - ../data/uploads:/uploads:rw
    environment:
      ALLOWED_PATHS: "/data,/uploads"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  linear:
    image: mcp/linear:latest
    build:
      context: ..
      dockerfile: ./servers/linear-mcp-server/Dockerfile
    container_name: mcp-linear-dev
    networks:
      - mcp-net
    env_file:
      - ../secrets/linear.env
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  mcp-net:
    name: mcp-network
    external: true
